export const SET_USERS = 'SET_USERS';
export const FETCH_SET_USERS ='FETCH_SET_USERS';

export const ADD_USERS = 'ADD_USERS';
export const FETCH_ADD_USERS = 'FETCH_ADD_USERS';

export const UPDATE_USERS = 'UPDATE_USERS';

export const USERS_FETCHING = 'USERS_FETCHING';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';

export const SET_PROFILE = 'SET_PROFILE';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const FETCH_UPDATE_PROFILE = 'FETCH_UPDATE_PROFILE';

export const SET_FIRST_NAME_TEXT = 'SET_FIRST_NAME_TEXT';
export const SET_LAST_NAME_TEXT = 'SET_LAST_NAME_TEXT';

export const SET_FETCH_ERROR = 'SET_FETCH_ERROR';

export const SET_RESULT = 'SET_RESULT';
export const SET_RESULT_FETCHING = 'SET_RESULT_FETCHING';