const types = {
    SET_USERS: 'SET_USERS',
    FETCH_SET_USERS: 'FETCH_SET_USERS',
    ADD_USERS: 'ADD_USERS',
    FETCH_ADD_USERS: 'FETCH_ADD_USERS',
    UPDATE_USERS: 'UPDATE_USERS',
    USERS_FETCHING: 'USERS_FETCHING',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_TOTAL_PAGES: 'SET_TOTAL_PAGES',

    SET_PROFILE: 'SET_PROFILE',
    FETCH_UPDATE_PROFILE: 'FETCH_UPDATE_PROFILE',

    SET_REDIRECT_PROFILE_TO_HOME_PAGE: 'REDIRECT_TO_HOME_PAGE',
    SET_REDIRECT_RESULT_TO_HOME_PAGE: 'REDIRECT_TO_HOME_PAGE',

    SET_FIRST_NAME_TEXT: 'SET_FIRST_NAME_TEXT',
    SET_LAST_NAME_TEXT: 'SET_LAST_NAME_TEXT',

    SET_RESULT: 'SET_RESULT',
    SET_RESULT_FETCHING: 'SET_RESULT_FETCHING',
}

export default types;